services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"

  catalog:
    image: "catalog:latest"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/catalog"
      SPRING_DATASOURCE_USERNAME: "catalog"
      SPRING_DATASOURCE_PASSWORD: "catalog"
    depends_on:
      - db

  order:
    image: "order:latest"
    ports:
      - "8081:8081"
    environment:
      CATALOG_URL: "http://catalog:8080"
    depends_on:
      - catalog
